### ISSUE TITLE
issue/1-todo-list

### ISSUE THREAD

**Issue by QuentinHacourt** [QuentinHacourt/productivity-js#1]
# Todo List

As a user, I want to have a todo list so i can focus on what tasks should be done.

I should be able to perform the following actions:

- [x] add items to the todo list
- [x] get an overview of all items on the todo list
- [x] edit items on the todo list
- [x] delete items from todo list

Todo List Items should have the following properties:

- title
- description
- deadline
